name: Deploy Spring Boot to Railway

on:
  push:
    branches:
      - main  # Chạy khi có commit mới trên branch main

jobs:
  deploy:
    runs-on: windows-latest  # ✅ Chạy trên Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_API_KEY }}
          railway up
